### ISSUE TITLE
DBCreator.py crash using Python3.7 on OSX

### ISSUE THREAD

**Issue by Scoubi** [BloodHoundAD/BloodHound-Tools#20]
Installed the lastest Python 3.7 and install dependencies using `pip3.7 install -r req.txt`
I then launch DBCreator and get the following : 
```
$ python3.7 DBCreator.py 
================================================================
BloodHound Sample Database Creator
================================================================

Documented commands (type help <topic>):
========================================
clear_and_generate  connect   exit      help       setnodes
cleardb             dbconfig  generate  setdomain

(Cmd) connect
Database Connection Successful!
(Cmd) generate
Starting data generation with nodes=500
Populating Standard Nodes
Traceback (most recent call last):
  File "DBCreator.py", line 806, in <module>
    MainMenu().cmdloop()
  File "DBCreator.py", line 69, in cmdloop
    cmd.Cmd.cmdloop(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "DBCreator.py", line 200, in do_generate
    self.generate_data()
  File "DBCreator.py", line 256, in generate_data
    sid=cs(512), gname=cn("DOMAIN ADMINS"))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/work/simple.py", line 217, in run
    self._autoResult._run(query, parameters, self._config.database, self._config.default_access_mode, self._bookmarks, **kwparameters)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/work/result.py", line 101, in _run
    self._attach()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/work/result.py", line 202, in _attach
    self._connection.fetch_message()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/io/_bolt4x0.py", line 330, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neo4j/io/_bolt4x0.py", line 518, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.ConstraintError: Node(0) already exists with label `Base` and property `objectid` = 'S-1-5-21-883232822-274137685-4173207997-512'
```

**Comment by byt3bl33d3r** [comment]
Fixed in https://github.com/BloodHoundAD/BloodHound-Tools/pull/28
